# Generated by Django 4.2.30 on 2026-07-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skillregistry_userprofile_contributionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSpawnTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('readme_template', models.TextField(blank=True)),
                ('license_template', models.TextField(blank=True)),
                ('tech_stack_tags', models.ManyToManyField(blank=True, to='core.skillregistry')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSpawnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SPAWNING', 'Spawning'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('result_repository_url', models.URLField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_proprietary_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietaryproduct')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectspawntemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawn_requests', to='core.userprofile')),
            ],
        ),
    ]
