# Generated by Django 4.2.30 on 2026-07-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectspawntemplate_projectspawnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('open_issues', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('health_score', models.FloatField(default=0.0)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='core.opensourcealternative')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_to_cla', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opensourcealternative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
            options={
                'unique_together': {('user', 'alternative')},
            },
        ),
    ]
